# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 18:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0004_auto_20161222_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='idproduct',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flowers.Catalog'),
        ),
        migrations.AlterField(
            model_name='order',
            name='iduser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
